name: fima_theia_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  go_router: ^13.2.0
  http: ^1.6.0
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  intl: ^0.19.0
  table_calendar: ^3.0.9
  image_picker: ^1.0.7
  camera: ^0.10.5+5
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1
  local_auth: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo.png
